version: '3.8'

networks:
  banco:
    name: banco
  web:
    name: web

services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: "laravel_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - banco
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: "laravel_redis"
    restart: always
    networks:
      - banco

  react:
    build:
      context: ../organ-donation-web # Ajusta o caminho para a pasta externa
      dockerfile: Dockerfile
    container_name: "react_frontend"
    ports:
      - "3000:3000"
    volumes:
      - ../organ-donation-web:/app # Ajusta o volume para refletir a estrutura externa
    working_dir: /app
    command: ["npm", "start"]
    networks:
      - web

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "laravel_api"
    restart: always
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:/dFfGgRrG6InaZo+2y3ifa6fCSvQ5efd8fbcGaQA40o=
    depends_on:
      - db
      - redis
    networks:
      - banco
      - web
    ports:
      - "8000:8000"
    command: >
      sh -c "
      php artisan config:cache &&
      php artisan migrate:fresh --seed &&
      php-fpm
      "

  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: "laravel_nginx"
    restart: always
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks: 
      - web
    ports:
      - "80:80"

volumes:
  db_data:
